AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: 'baseline-styra-opa-bucket'
      LoggingConfiguration:
        DestinationBucketName: 'my-logging-bucket'
        LogFilePrefix: 's3-logs-baseline-styra-opa-bucket'