AWSTemplateFormatVersion: "2010-09-09"

Resources:
  UserWithPolicy:
    Type: AWS::IAM::User
    Properties: 
      PermissionsBoundary: 'arn:aws:iam::555555555555:policy/s3_deny_permissions_boundary'
      Policies: 
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Deny
                Action:
                  - 'ec2:*'
                Resource: '*'
          PolicyName: test
      UserName: WithPolicy

  UserWithManagedPolicy:
    Type: AWS::IAM::User
    Properties: 
      PermissionsBoundary: 'arn:aws:iam::555555555555:policy/s3_deny_permissions_boundary'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSDenyAll
      UserName: WithManagedPolicy
