AWSTemplateFormatVersion: "2010-09-09"
Resources:
  IAMRoleTest:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'excluded-cfn-hooks-role'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com