AWSTemplateFormatVersion: "2010-09-09"

Resources:
  UserWithEc2InlinePolicy:
    Type: AWS::IAM::User
    Properties: 
      Policies: 
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'ec2:*'
                Resource: '*'
          PolicyName: test
      UserName: WithInlineEc2Policy