AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EksCluster:
    Type: AWS::EKS::Cluster
    Properties: 
      RoleArn: "<MY_EKS_SERVICE_ROLE_ARN>"
      ResourcesVpcConfig:
        SubnetIds: ["<MY_SUBNET_ID>"]
      Logging: 
        ClusterLogging: 
          EnabledTypes:
          - {Type: audit}
          - {Type: authenticator}