name: Generate Assets

on:
  workflow_run:
    workflows: [OPA Tests]
    types:
      - completed

jobs:
  opa-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Install and run cfn cli
      run: |
        cd hooks
        pip install --quiet cloudformation-cli cloudformation-cli-python-plugin
        cfn submit --dry-run

    - name: Upload zip file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: hook-package-zip
        path: hooks/styra-opa-hook.zip
