name: Generate Assets

on:
  workflow_run:
    workflows: [OPA Tests]
    types:
      - completed

jobs:
  opa-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v23

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Install and run cfn cli
      run: |
        cd hooks
        pip install --quiet cloudformation-cli cloudformation-cli-python-plugin
        cfn submit --dry-run

    - name: Git diff
      id: git_diff
      run: |
        FILE_CHANGED=true
        if ! git diff --no-ext-diff --quiet --exit-code; then
          FILE_CHANGED=false
        fi
        echo "::set-output name=git_changes::$(echo $FILE_CHANGED)"

    - name: Commit changes if any
      if: steps.git_diff.outputs.git_changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -a -m "automation: update hook zip file"
        git push
